name: 'Architect Deploy'
description: 'Deploys an Architect app to AWS'
inputs:
  aws_access_key_id:
    required: true
  aws_secret_access_key:
    required: true
runs:
  using: "composite"
  steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install
        shell: bash
        run: npm i

      - name: Staging Deploy
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: npx arc deploy --staging
        env:
          CI: true
          AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}

      - name: Production Deploy
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: npx arc deploy --production
        env:
          CI: true
          AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
